# Generated by Django 6.0.2 on 2026-03-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=100)),
                ('Bookauthor', models.CharField(max_length=100)),
                ('Bookpage', models.BigIntegerField()),
                ('Bookprice', models.IntegerField()),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
